version: '3'
services:
  db:
    #container_name: db
    image: mariadb:11
    restart: always
    environment:
      MARIADB_DATABASE: 'debunker'
      MARIADB_ROOT_PASSWORD: '309urje4'
    expose:
      - '3306'
    volumes:
      - '/cold_storage/data/debunker:/var/lib/mysql'
    networks:
      static-network:
        ipv4_address: 10.5.0.5
  debunker:
    #container_name: debunker
    build: '.'
    restart: always
    ports:
      - '9001:2000'
    depends_on:
      - db
    networks:
      static-network:
        ipv4_address: 10.5.0.6
    tty: true
    stdin_open: true
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1